server:
  port: 9030
  servlet:
    context-path: /order-service
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/izayoi_order?useSSL=false&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123233
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
logging:
  level:
    root: info
mybatis-plus:
  mapper-locations: classpath:com/izayoi/common/mapper/xml/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl